Repository hmcts/hmi-apim-infrastructures, pull requests merged in 2023-08, with the labels that each got.

#4 HMIS-1217 Add CaTH Policy files to SDS APIM
  api-management-logger.tf
  api-management-product.tf
  demo.tfvars
  dev.tfvars
  resources/policy-files/CaTH/api-op-publication-health-policy.xml
  resources/policy-files/CaTH/api-op-publication-policy.xml
  resources/policy-files/policies.json
  resources/policy-files/product-policy.xml
  sbox.tfvars
  stg.tfvars
  test.tfvars
  variables.tf
Labels: add-or-update

#6 HMIS-1217 Fix deployment for SDS test
  ithc.tfvars
  main.tf
Labels: add-or-update

#10 Change base url for endpoints
  infrastructure/main.tf
Labels: add-or-update, ns:hmi, prd:hmi, rel:hmi-apim-pr-10

#11 Revert base url change
  infrastructure/main.tf
Labels: destroy, ns:hmi, prd:hmi, rel:hmi-apim-pr-11

#12 HMIS-1227 setup smoke tests
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  config/pmd/ruleset.xml
  src/functionalTest/java/uk/gov/hmcts/reform/hmi/pip/SampleFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmi/controllers/GetWelcomeTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/hmi/openapi/OpenAPIPublisherTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/hmi/controllers/SampleSmokeTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/hmi/helper/HeaderHelper.java
  src/smokeTest/java/uk/gov/hmcts/reform/hmi/helper/RestClientHelper.java
  src/smokeTest/java/uk/gov/hmcts/reform/hmi/internal/HealthCheckSmokeTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/hmi/pip/HealthCheckSmokeTest.java
  src/smokeTest/resources/application-smoke.yaml
Labels: ns:hmi, prd:hmi, rel:hmi-apim-pr-12

#13 HMIS-1225 added functional tests for PIP
  Jenkinsfile_nightly
  README.md
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/hmi/helper/HeaderHelper.java
  src/functionalTest/java/uk/gov/hmcts/reform/hmi/helper/RestClientHelper.java
  src/functionalTest/java/uk/gov/hmcts/reform/hmi/pip/PostPublicationTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/hmi/pip/SampleFunctionalTest.java
  src/functionalTest/resources/application-functional.yaml
  src/functionalTest/resources/pip/invalid-care-standards-list.json
  src/functionalTest/resources/pip/successful-care-standards-list.json
  src/test/resources/application.yaml
Labels: ns:hmi, prd:hmi, rel:hmi-apim-pr-13

#14 Updated cron timer for nightly
  Jenkinsfile_nightly
Labels: ns:hmi, prd:hmi, rel:hmi-apim-pr-14

#15 Updated nightly
  Jenkinsfile_nightly
Labels: ns:hmi, prd:hmi, rel:hmi-apim-pr-15

#18 HMIS-1241 updated default role
  infrastructure/api-management.tf
  infrastructure/resources/policy-files/api-policy.xml
  infrastructure/variables.tf
Labels: add-or-update, ns:hmi, prd:hmi, rel:hmi-apim-pr-18

#17 HMIS-1248 VH Endpoints Migration Part 1
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/renovate.json
  .github/stale.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  infrastructure/api-management-policy-file-reader.tf
  infrastructure/data.tf
  infrastructure/resources/policy-files/Video-Hearing/api-op-create-vh-policy.xml
  infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-id-policy.xml
  infrastructure/resources/policy-files/Video-Hearing/api-op-retrieve-vh-by-user-policy.xml
  infrastructure/resources/policy-files/Video-Hearing/api-op-update-vh-by-id-policy.xml
  infrastructure/resources/policy-files/Video-Hearing/api-op-vh-groupid-hearing-policy.xml
  infrastructure/resources/policy-files/policies.json
Labels: add-or-update, ns:hmi, prd:hmi, rel:hmi-apim-pr-17

#20 HMIS-1247 Terraform format github action
  .github/workflows/terraform_format.yml
  infrastructure/api-management-policy-file-reader.tf
  infrastructure/api-management-product.tf
  infrastructure/api-management.tf
  infrastructure/data.tf
  infrastructure/demo.tfvars
  infrastructure/dev.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/sbox.tfvars
  infrastructure/stg.tfvars
  infrastructure/test.tfvars
  infrastructure/variables.tf
Labels: add-or-update, ns:hmi, prd:hmi, rel:hmi-apim-pr-20

#16 HMIS-1243 Update base url
  infrastructure/api-management.tf
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/resources/api-spec/hmi-api-health.json
  infrastructure/sbox.tfvars
  infrastructure/stg.tfvars
  infrastructure/test.tfvars
  infrastructure/variables.tf
Labels: add-or-update, ns:hmi, prd:hmi, rel:hmi-apim-pr-16

#26 HMIS-1250 Migrate Video Hearing Endpoints Part3
  infrastructure/resources/policy-files/Video-Hearing/api-op-delete-vh-by-id-policy.xml
  infrastructure/resources/policy-files/Video-Hearing/api-op-vh-cancel-hearing-policy.xml
  infrastructure/resources/policy-files/Video-Hearing/api-op-vh-clone-hearing-policy.xml
  infrastructure/resources/policy-files/Video-Hearing/api-op-vh-health-policy.xml
  infrastructure/resources/policy-files/policies.json
Labels: destroy, ns:hmi, prd:hmi, rel:hmi-apim-pr-26

#29 Fix Video Hearing response code
  infrastructure/resources/policy-files/policies.json
Labels: add-or-update, ns:hmi, prd:hmi, rel:hmi-apim-pr-29
