Repository hmcts/hmi-apim-infrastructures, pull requests merged in 2025-07, with the labels that each got.

#231 PUB-2953 Fix build
  config/owasp/suppressions.xml
Labels: ns:hmi, prd:hmi, rel:hmi-apim-pr-231

#232 PUB-2959 - Dependency Updates
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  infrastructure/providers.tf
Labels: ns:hmi, prd:hmi, stg/no-changes, prod/no-changes, rel:hmi-apim-pr-232

#233 Updated suppressions
  config/owasp/suppressions.xml
Labels: ns:hmi, prd:hmi, rel:hmi-apim-pr-233

#213 PUB-2886 Implement Strict-Transport-Security Correctly
  infrastructure/resources/policy-files/api-policy.xml
Labels: ns:hmi, prd:hmi, stg/add-or-update, prod/add-or-update, rel:hmi-apim-pr-213
